jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
jwtpassword:
  source: ENC(Z+m7jtTf9w1/6yd2NAibo0CSCb89JvkPf96SUKdqxQflQwIAGvr781dHGdToS0XvTUCrRADcGTHCVyF1VaF9nh4j8yql3Z1Ubef+BI0d+gQ=)

coolsms:
  api-key: ENC(/dfc/hVOB+ZrZLxajUlpwrhRCUcpBXxkLMUJqf5zaAo=)
  api-secret: ENC(81triyc/kAD+hm1xonupRz65Dunttouv40tfyVk/2zFj8J6ws4jwaf6y/rJN4zYt)
  domain : https://api.solapi.com
  phone-number: ENC(z/wRpfredxFKff/lsjozmL+EeOPpcJS0) # 발신번호

spring:
  server-url:
    base: http://localhost:8080
  mvc:
    path match:
      matching-strategy: ant_path_matcher #????????? ???? ???? ???
      #    jsp??
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    open-in-view: false
    show-sql: true
  datasource:
    username: ENC(tBOBH7aOREOgndD7L9SZOB311JqKHImI)
    password: ENC(N1H6zRdGq5YiEpqkTKXG5g==)
    driver-class-name: oracle.jdbc.OracleDriver
    url: ENC(Q8RI4B/WgDTy3GxENPg1/jPBuPqEdLOFs7KPV4pL87j5cu2r4tR8bJF757DaEjla)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(IZt11MAiQJTiwic1gfLsKTV1TwEKpdcSrpQ3WJRwKKg=)
    password: ENC(f6AELtlUmP71YUZkC8hva99HDr/Fbej+gZOIlw4S9MU=)
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
#              Identity Manager 서버가 SSL을 사용하여 SMTP와 통신하도록 지시합니다.

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /mvc-docs.html
  version: 1.0.0

file:
  upload:
    directory: c:/uploads/semi-project-shop/